
project_id = "jpgdtopuuzlzxbnvodfk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[functions.delete-user]
verify_jwt = true
